Add asyncio support for SQLAlchemy
spoqa/ormeasy pull request #3
Opened 2021-04-02 08:01 UTC by kanghyojun

- SQLAlchemy 1.4 now supports asyncio module. It changes its internal api to deal with connection.
- So `ormeasy` needs to handle async version connection.
- Since [asynccontextmanager][] introduced in Python 3.7, It raise `RuntimeError` if Python version is lower than 3.7.
 
[asynccontextmanager]: https://docs.python.org/3/library/contextlib.html#contextlib.asynccontextmanager

2021-04-02 08:18 UTC, pbzweihander requested changes

2021-04-02 08:18 UTC, pbzweihander commented on ormeasy/asyncsqlalchemy.py
> +       async fx_connection(request, fx_engine: AsyncEngine):
```suggestion
       async def fx_connection(request, fx_engine: AsyncEngine):
```

2021-04-05 01:07 UTC, kanghyojun commented on ormeasy/asyncsqlalchemy.py
> +       async fx_connection(request, fx_engine: AsyncEngine):
omg...

2021-04-05 01:55 UTC, Jhuni0123 approved these changes

2021-04-06 02:32 UTC, pbzweihander approved these changes

2021-04-06 02:32 UTC, merged

2021-04-06 02:33 UTC, kanghyojun commented
Thanks :)